name: Run Lexer Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Lexer Test Case 1
        run: python -m tests.lexer.LexerUnitTest 1

      - name: Run Lexer Test Case 2
        run: python -m tests.lexer.LexerUnitTest 2

      - name: Run Lexer Test Case 3
        run: python -m tests.lexer.LexerUnitTest 3

      - name: Run Lexer Test Case 4
        run: python -m tests.lexer.LexerUnitTest 4

      - name: Run Lexer Test Case 5
        run: python -m tests.lexer.LexerUnitTest 5

      - name: Run Parser Test Case 1
        run: python -m tests.parser.ParserTest 